from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class IRepository[TInput, TResponse](Protocol):
    """Interface (port) para persistência."""

    # O uso de TInput aqui como parâmetro exige contravariância
    def add(self, entity: TInput) -> None: ...

    def update(self, entity: TInput) -> None: ...

    def get_by_id(self, id: UUID) -> TResponse | None: ...
    def delete(self, id: UUID) -> None: ...
    def search(self, filter: dict[str, Any]) -> list[TResponse]: ...
    def list_all(self) -> list[TResponse]: ...
